### PR TITLE
Convert between Windows and IANA times

### PR DESCRIPTION
**Pull request by willyboy**
Windows expects different timezone strings than other OSes. For example, America/New_York on a Mac would need to be Eastern Standard Time on a Windows machine. This PR fixes the fact that this wasn't working.

It's dependent on this PR from windows-iana: https://github.com/rubenillodo/windows-iana/pull/3

### CODE REVIEW

**Comment by willyboy** [comment]
@capaj https://github.com/rubenillodo/windows-iana/pull/3 has been merged. Is this PR acceptable to merge?

**Review by capaj — APPROVED** [review]

**Comment by capaj** [comment]
@willyboy thanks for a mention. I wouldn't notice the PR without it.

**Comment by capaj** [comment]
@willyboy published as 0.2.0

**Comment by willyboy** [comment]
@capaj Thanks! Really appreciate it :)

**Pull request merged**
